#!/bin/sh

test="$1"
wait_services_seconds=5

variant() {
  if /sbin/init --help 2>&1 | grep upstart >/dev/null
  then
    echo upstart
  else
    echo sysv
  fi
}

run_test() {
  if sh -c "$test"; then
    echo 'hijack-init: tests exited without error'
    true
  else
    echo 'hijack-init: tests exited with nonzero exit status'
    false
  fi
}

upstart_test_subshell() {
  sleep 1 # give upstart time to start up

  init 2 # enter runlevel 2

  sleep $wait_services_seconds # give services time to spawn

  if run_test; then
    result="true"
  else
    result="false"
  fi

  # replace /sbin/init with our own version, saving the original
  mv /sbin/init /sbin/original-init
  cat <<INIT >> /sbin/init
#!/bin/bash
rm /sbin/init
mv /sbin/original-init /sbin/init
/bin/$result
INIT
  chmod a+x /sbin/init


  # tell upstart to exec to /sbin/init
  kill 1
}

if [ "$(variant)" = "upstart" ]; then
  upstart_test_subshell &

  exec /sbin/init
else # sysv init
  /sbin/init --init &

  sleep $wait_services_seconds # give services time to spawn

  run_test
fi
